version: 'appveyor-t{build}'
image: Visual Studio 2017
configuration:
- Release
platform:
- x64
install:
- cmd: |-
    git submodule update --init --recursive
before_build:
- cmd: |-
    cd C:/projects
    git clone https://github.com/libusb/libusb.git
    cd libusb
    msbuild msvc/libusb_2017.sln /p:Configuration=Release,Platform=x64
    cd C:/projects/twili/twib
    mkdir build
    cd build
    cmake --version
    cmake .. -DLIBUSB_1_LIBRARY=C:/projects/libusb/x64/Release/lib/libusb-1.0.lib -DLIBUSB_1_INCLUDE_DIR=C:/projects/libusb/libusb/ -DLIBUSB_1_LIBRARIES=C:/projects/libusb/x64/Release/lib/libusb-1.0.lib -DLIBUSB_1_INCLUDE_DIRS=C:/projects/libusb/libusb/ -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_BUILD_TYPE=Release
build:
  project: c:/projects/twili/twib/build/twib.sln
  parallel: true
artifacts:
- path: twib/build/twib/Release/twib.exe
  name: twib_win64.exe
- path: twib/build/twibd/Release/twibd.exe
  name: twibd_win64.exe
#after_build:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
