addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libusb-1.0.0
    - libusb-1.0.0-dev
    - python3-pip
    - liblz4-dev
    - squashfs-tools
    - g++-8
env:
  global:
    - LIBTRANSISTOR_REPO=misson20000/libtransistor
    - LIBTRANSISTOR_VERSION=v2.2.0-rc6
language: cpp
jobs:
  include:
  - stage: Build
    os: linux
    name: "twili"
    env: TARGET="twili" PLATFORM="nx-transistor64"
    install: "./.travis/twili_install.sh"
    script: make LIBTRANSISTOR_HOME=$PWD/libtransistor/ PATH="$PWD/fr/opt/devkitpro/tools/bin/:$PATH"
    before_deploy: "./.travis/twili_before_deploy.sh"
  - os: linux
    name: "twib_linux64"
    env: TARGET="twib" PLATFORM="linux64"
    script: "./.travis/twib.sh -DCMAKE_CXX_COMPILER=g++-8"
    before_deploy: "./.travis/twib_before_deploy.sh"
  - os: osx
    name: "twib_osx64"
    osx_image: xcode10.2
    compiler: clang
    env: TARGET="twib" PLATFORM="osx64"
    script:
    - brew update
    - brew install llvm
    - export PATH="$(brew --prefix llvm)/bin:$PATH"
    - "./.travis/twib.sh -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS=-std=c++17 -DWITH_LAUNCHD=ON"
    before_deploy: "./.travis/twib_before_deploy.sh"
deploy:
  - provider: releases
    skip-cleanup: true
    api_key: $GITHUB_TOKEN
    draft: true
    tag_name: $TRAVIS_TAG
    file_glob: true
    file: deploy/*
    on:
      tags: true
